POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "title3",
    "author": "author5",
    "url": "testurl.com",
    "likes": 115,
    "userId": "6002b8e613e9a811c416c250"
}